# Generated by Django 4.2.3 on 2023-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallerys',
            },
        ),
    ]
