# Generated by Django 4.2.3 on 2023-07-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image_alter_house_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='houses', to='home.image', verbose_name='images'),
        ),
    ]
