# Generated by Django 4.2.3 on 2023-07-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_house_image_house_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='houses', related_query_name='house', to='home.image', verbose_name='images'),
        ),
    ]
