# Generated by Django 4.2.3 on 2023-07-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_house_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
    ]
