# Generated by Django 4.2.3 on 2023-07-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
