# Generated by Django 4.2.3 on 2023-07-17 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_review_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.house', verbose_name='house'),
        ),
    ]
