# Generated by Django 4.2.2 on 2023-06-29 10:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default=None, max_length=250, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=None, max_length=250, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='surname',
            field=models.CharField(default=None, max_length=250, verbose_name='surname'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
