# Generated by Django 4.2.3 on 2023-07-07 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='email'),
        ),
    ]
